name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 0.3.4+1
homepage: "https://supabase.io"
repository: "https://github.com/supabase/supabase-dart"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_client: ^0.0.1-dev.4
  gotrue: ^0.2.2
  postgrest: ^0.1.10+1
  realtime_client: ^0.1.15
  storage_client: ^0.0.6+2

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.9
