name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 1.0.0-dev.8
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/supabase-dart'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  functions_client: 1.0.0-dev.4
  gotrue: 1.0.0-dev.4
  http: ^0.13.4
  postgrest: 1.0.0-dev.4
  realtime_client: 1.0.0-dev.3
  storage_client: 1.0.0-dev.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.9
  web_socket_channel: ^2.2.0
